### PR TITLE
Fixed behavior of failed dynamic import

### LINKED ISSUE #32: [Floating 2/3] [Playground] - Failed to fetch dynamically imported module: .../assets/PlaygroundElement-2f0a3451.js
### Describe the bug

Sometimes (2 of 3 cases) this error occurs while user opening playgroud

### To Reproduce

**Test steps:**
- Open API Operation;
- Click [Playground] button;

**ER:**
"Playground" side-bar opened

**AR:**

Image

### Version

38 (Drop2)

### Logs

```js
Unexpected Application Error!
Failed to fetch dynamically imported module: .../assets/PlaygroundElement-2f0a3451.js
TypeError: Failed to fetch dynamically imported module: .../assets/PlaygroundElement-2f0a3451.js
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by JayLim2**
Closes #32

### CODE REVIEW

**Review by CountRedClaw — APPROVED** [review]

File: packages/shared/src/components/ModuleFetchingErrorBoundary/ModuleFetchingErrorDialog.tsx [hunk 1]
```diff
@@ -27,24 +27,22 @@ export const ModuleFetchingErrorPopup: FC<PropsWithChildren> = () => (
...
+    <DialogTitle sx={{ fontSize: 15, fontWeight: 600, color: 'black' }}>
       APIHUB UI is out of date
     </DialogTitle>
     <DialogContent>
-      <Typography variant='body2' textAlign='center'>
-        The version of APIHUB UI is out of date.
+      <DialogContentText
+        variant="body2"
+        sx={{ color: 'black' }}
+        data-testid="ConfirmationDialogContent"
```
Comment (CountRedClaw) [inline packages/shared/src/components/ModuleFetchingErrorBoundary/ModuleFetchingErrorDialog.tsx:37]: wrong testid value

**Review by CountRedClaw — APPROVED** [review]
