### PR TITLE
fix: can not find data from recently published packages

### LINKED ISSUE #594: [Bug][FE] Clearing browser cache resolves incorrect search results
### Describe the bug

Preconditions: GraphQG specifications are published in the system

### To Reproduce

1. Open Global search
2. Execute GraphQG API Operation search (status=released)
3.  Don't close the tab, after some period of time execute execute GraphQG API Operation search (status=draft)

**ER: results can be found (at least after page update)
AR: results can be found only after deletion browser cache (which is not obvious for user)**

### Version

Frontend v. 3.4.1-dev.20260403104459
API Processor v. 5.1.0-dev.20260402190639

### Logs

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by iurii-golovinskii**

### CODE REVIEW

**Review by makeev-pavel — APPROVED** [review]

File: packages/portal/src/routes/root/BasePage/GlobalSearchPanel/SearchFilters.tsx [hunk 1]
```diff
@@ -99,9 +99,14 @@ type SearchFilters = {
 }
 
 export const SearchFilters: FC<SearchFilters> = memo(({ enabledFilters }) => {
-  const oneYearAgo = new Date()
-  oneYearAgo.setFullYear(oneYearAgo.getFullYear() - 1)
-  const defaultPublicationDatePeriod = [oneYearAgo.toISOString(), new Date().toISOString()]
+  const defaultPublicationDatePeriod = useMemo(() => {
```
Comment (b41ex) [inline packages/portal/src/routes/root/BasePage/GlobalSearchPanel/SearchFilters.tsx:103]: We already have similar logic in `formatPublicationDate`, need to reuse it instead of copy-pasting it.

**Review by b41ex — CHANGES_REQUESTED** [review]

**Review by b41ex — APPROVED** [review]
