### PR TITLE
fix(portal): prevent 404 when opening operations compare

### LINKED ISSUE #524: [Bug]: [FE] Error 404 appears when navigating to operations compare (Failed CI tests)
### Describe the bug

On a **clean** test data, on the **first** attempt, two end-to-end UI autotests fail:
- [P-COPODFI-5] Checking filters condition on the Compare operations page in Doc view after swapping
- [P-COPORFI-2] Filtering operations by Documents on the Compare operations page in Raw view

### To Reproduce

**A**. Run local autotests by command
```
npx playwright test --project=Portal --grep="P-COPORFI-2|P-COPODFI-5" --retries=0 --trace=on
```
or
**B**. Run autotests on [GitHub CI](https://github.com/Netcracker/qubership-apihub/actions/workflows/run-e2e-tests.yml). In the "Playwright test command CLI arguments" field, specify the following parameters:
```
--project=Portal --grep="P-COPORFI-2|P-COPODFI-5" --retries=0
```
**ER:** Tests should pass.
**AR:** Tests fail.

Image

### Version

dev

### Logs

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by iurii-golovinskii**
## Summary

Fixes incorrect or transient **404** behavior when navigating to **operations compare** by aligning query timing with resolved package revisions, tightening React hook dependencies, and treating expected “not found” responses on optional comparison endpoints as non-fatal.

## Changes

- **Versions comparison query**: wait until origin/changed revision resolution finished before enabling the comparison request (`useVersionsComparisons`).
- **Operation view**: include `originOperation` in memo dependencies so compare UI updates when the origin operation changes (`OperationContent`).
- **Optional compare endpoints**: `ignoreNotFound` + `retry` for internal comparison documents and operation changes summary hooks.

## Test plan

- [ ] Open operations compare between two versions where revision metadata resolves asynchronously; confirm no 404 flash / failed navigation.
- [ ] Toggle/compare operations where only the origin side changes; confirm UI refreshes correctly.
- [ ] Regression: normal compare still loads when all resources exist (no silent empty states where data should appear).

### CODE REVIEW

File: packages/portal/src/api-hooks/InternalDocuments/useComparisonInternalDocumentsByPackageVersion.ts [hunk 1]
```diff
@@ -53,6 +53,7 @@ export function useComparisonInternalDocumentsByPackageVersion(
         ? getComparisonInternalDocumentsByPackageVersion(options)
         : Promise.resolve([])
```
Comment (iurii-golovinskii) [inline packages/portal/src/api-hooks/InternalDocuments/useComparisonInternalDocumentsByPackageVersion.ts]: Image

**Review by vOrigins — APPROVED** [review]

**Review by makeev-pavel — APPROVED** [review]

**Review by JayLim2 — APPROVED** [review]
